"""
State models and schemas for the FormaGuard LangGraph Agent Loop.
Defines typed dictionaries and Pydantic models for bounding boxes, thermal metrics,
canopy spatial trees, and Autodesk Forma element geometry payloads.
"""

from typing import List, Dict, Any, Optional, TypedDict, Annotated
import operator
from pydantic import BaseModel, Field


class BoundingBox(BaseModel):
    """3D/2D bounding box extracted from Autodesk Forma canvas."""
    min_x: float = Field(..., description="Minimum longitude or local easting")
    min_y: float = Field(..., description="Minimum latitude or local northing")
    max_x: float = Field(..., description="Maximum longitude or local easting")
    max_y: float = Field(..., description="Maximum latitude or local northing")
    crs: str = Field(default="EPSG:3857", description="Coordinate Reference System (e.g. EPSG:3857 or UTM)")
    elevation_min: Optional[float] = Field(default=0.0, description="Ground elevation level")
    elevation_max: Optional[float] = Field(default=50.0, description="Max building height in scene")


class HeatPoint(BaseModel):
    """2m street-level thermal measurement point."""
    x: float
    y: float
    temperature_celsius: float
    surface_temp_celsius: float
    humidity_pct: float
    heat_index_celsius: float
    solar_exposure_kwh_m2: float
    vulnerability_score: float  # 0.0 to 1.0


class TemperatureData(BaseModel):
    """Aggregated microclimate data from FortyGuard API."""
    average_ambient_celsius: float
    peak_surface_celsius: float
    mean_radiant_temp_celsius: float
    hotspots_count: int
    thermal_stress_level: str  # "Extreme", "High", "Moderate", "Low"
    heat_points: List[HeatPoint]
    timestamp: str


class CanopyElement(BaseModel):
    """Existing vegetation structure from OpenStreetMap / LiDAR."""
    id: str
    type: str  # "broadleaf_tree", "conifer", "shrub_belt", "urban_park"
    center: List[float]  # [x, y, z]
    radius_meters: float
    height_meters: float
    health_ndvi: float  # 0.0 to 1.0 Normalized Difference Vegetation Index


class CanopyData(BaseModel):
    """Existing urban canopy baseline."""
    existing_trees_count: int
    canopy_coverage_pct: float
    ndvi_mean: float
    trees: List[CanopyElement]


class ProposedIntervention(BaseModel):
    """Specific urban cooling intervention generated by the AI agent."""
    id: str
    category: str  # "canopy_tree", "bioswale", "cool_roof", "high_albedo_pavement", "pergola_shade"
    name: str
    target_corridor: str  # e.g. "Southern pedestrian promenade", "Eastern plaza courtyard"
    geometry_type: str  # "Point", "Polygon", "MultiPolygon", "glTF_Instance"
    coordinates: List[Any]
    dimensions: Dict[str, float]  # height, crown_diameter, albedo_factor, etc.
    estimated_cooling_celsius: float
    co2_sequestration_kg_yr: float
    cost_estimate_usd: float


class MitigationPlan(BaseModel):
    """Comprehensive urban heat mitigation plan evaluated by LangGraph."""
    summary_command: str  # e.g. "Add 15% tree canopy to the southern corridor and 3 high-albedo shade sails"
    overall_thermal_reduction_celsius: float
    target_canopy_increase_pct: float
    priority_level: str  # "Urgent", "High", "Medium"
    interventions: List[ProposedIntervention]
    rationale: str


class FormaGeometryElement(BaseModel):
    """JSON structure directly compliant with Autodesk Forma Elements SDK."""
    urn: str
    element_type: str  # "tree", "vegetation_patch", "surface_material", "shade_structure"
    name: str
    properties: Dict[str, Any]
    transform_matrix: List[float]  # 4x4 matrix (16 floats)
    geometry: Dict[str, Any]  # GeoJSON / glTF mesh reference / Forma primitive


class FormaActuatorPayload(BaseModel):
    """Output payload passed to Forma.render.addGeometry / Forma.elements.integrate."""
    status: str
    version: str = "2024.1"
    bounding_box: BoundingBox
    elements_to_add: List[FormaGeometryElement]
    elements_to_update: List[Dict[str, Any]] = []
    simulation_metadata: Dict[str, Any]


class AgentMessage(BaseModel):
    role: str  # "user", "assistant", "system", "tool"
    content: str
    timestamp: str
    tool_call: Optional[Dict[str, Any]] = None


class AgentState(TypedDict):
    """
    LangGraph state schema for multi-agent thermal risk and actuation loop.
    Annotated with reducers for list accumulation.
    """
    messages: Annotated[List[Dict[str, Any]], operator.add]
    bounding_box: Dict[str, Any]
    user_prompt: str
    temperature_data: Optional[Dict[str, Any]]
    canopy_data: Optional[Dict[str, Any]]
    thermal_risk_score: Optional[float]
    identified_hotspots: Optional[List[Dict[str, Any]]]
    mitigation_plan: Optional[Dict[str, Any]]
    forma_payload: Optional[Dict[str, Any]]
    active_agent: Optional[str]
    iteration: int
    final_response: Optional[str]
